version: '3.3'
services:
  database:
    image: mysql:latest
    container_name: mysql_school_manager
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'school_manager'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
    ports:
      - '3307:3306'
    volumes:
      - '~/.volume/school-manager:/var/lib/mysql'